// Package message carries walkie's message identity, envelope helpers and
// receiver-side deduplication.
//
// Owning work item:
//
//	eka get walkie/sto:text-messaging
//
// # Identity and ordering
//
// Every message carries a ULID generated by the SENDER, not the coordinator.
// That placement is deliberate and load-bearing in two ways:
//
//   - It makes redelivery idempotent at the receiver. req:offline-delivery
//     specifies at-least-once delivery on the wire with deduplication at the
//     receiver; exactly-once is explicitly not attempted at the transport layer.
//     The way you get correctness is by making a duplicate harmless.
//   - It can be generated offline, with no coordination. That is exactly what
//     the client-side outbox needs when a message is composed while
//     disconnected.
//
// Ordering is per conversation, not global. req:text-messaging says so
// explicitly: a total order across the tailnet is not provided and must not be
// assumed by anything built on this package.
//
// # Timestamps
//
// Retain both the sender's send time and the coordinator's receive time. Clock
// skew across the fleet is expected, neither value alone is trustworthy, and
// req:text-messaging requires the skew stay visible to the user rather than
// being silently resolved in favour of one clock.
package message
