package message

import (
	"crypto/rand"
	"fmt"
	"sync"
	"time"
	"unicode/utf8"

	"github.com/oklog/ulid/v2"
)

// MaxBodyBytes is the receiver-enforced bound on one message body: at most
// 4096 bytes of UTF-8, exactly as the DirectMessage.body and
// BroadcastMessage.body field docs in walkie.v1 specify.
//
// Why a constant here when enforcement happens at the coordinator: the bound
// is a property of TEXT MESSAGING (req:text-messaging), not of one endpoint —
// the composing client wants it to warn its user before sending, the
// coordinator must reject rather than truncate on receipt, and sto:message-
// history will want it again for storage sizing. One definition in the owning
// package keeps those three from drifting.
//
// Rejection over truncation is not negotiable: a truncated message reads as
// delivered-but-wrong, which is worse than an error the sender can act on.
const MaxBodyBytes = 4096

// Message is one text message as every consumer of this package sees it:
// the composing client, the routing coordinator's tests, the receiving
// display model and — later — sto:message-history's store.
//
// It deliberately mirrors what travels on the wire (Envelope + payload,
// adr:003) without importing protobuf types: consumers never touch genproto
// to render or reason about a message, the same rule internal/presenceview
// applies to roster lines.
type Message struct {
	// ID is the SENDER-generated ULID (Envelope.message_id). It is the whole
	// dedup mechanism: delivery is at-least-once on the wire, so redelivery
	// is made harmless at the receiver by discarding IDs it has already
	// displayed. Never generated by the coordinator — see the package comment.
	ID string

	// Sender is the device that composed the message, named as the tailnet
	// resolves it. The coordinator takes it from the connection's resolved
	// identity, never from any payload field; a client fills it from its own
	// HelloAck device.
	Sender string

	// Recipient is the destination device name for a direct message; empty
	// means broadcast. The asymmetry mirrors the wire: BroadcastMessage has
	// no recipient field to mirror.
	Recipient string

	// Body is the message text, at most [MaxBodyBytes] bytes of UTF-8.
	Body string

	// SentAt is the sender's clock reading when it composed the message.
	// UNTRUSTWORTHY by design — fleet clock skew is expected — and retained
	// anyway, because req:text-messaging requires BOTH timestamps survive to
	// the user so skew stays legible instead of silently resolved.
	SentAt time.Time

	// ReceivedAt is the coordinator's clock reading stamped once at ingress.
	// The trustworthy half of the pair: one clock all devices agree on by
	// virtue of talking to the same coordinator. Never rewritten on replay —
	// the schema pins this ("stamped at ingress and never rewritten") and so
	// does the coordinator's routing code.
	ReceivedAt time.Time
}

// IsBroadcast reports whether msg is a broadcast (no named recipient).
func (m Message) IsBroadcast() bool { return m.Recipient == "" }

// Conversation keys are namespaced strings so a device literally named
// "broadcast" cannot collide with the broadcast conversation key below.
const (
	// dmKeyPrefix namespaces direct-message conversation keys.
	dmKeyPrefix = "dm:"

	// BroadcastConversation is the key of the one broadcast conversation:
	// every broadcast lands here, on every receiving device.
	BroadcastConversation = "broadcast"
)

// ConversationKey returns the per-conversation key for direct messages
// exchanged with peer. From any one device's perspective a DM conversation
// with a peer is ONE conversation regardless of direction — sent and received
// messages interleave in it — so the key derives from the peer name alone and
// needs no local identity.
//
// Ordering within the returned conversation is the ONLY ordering this package
// provides. See the package comment before building anything that wants more.
func ConversationKey(peer string) string {
	return dmKeyPrefix + peer
}

// idEntropy source state. ulid.Monotonic is not safe for concurrent use, so
// every NewID call takes the mutex; generation is not hot enough for the lock
// to matter at human messaging rates.
var (
	idMu      sync.Mutex
	idEntropy = ulid.Monotonic(rand.Reader, 0)
)

// NewID returns a fresh sender-side message identity: a ULID for time at.
//
// Monotonic entropy makes ULIDs generated within the same millisecond sort
// lexicographically in generation order — a convenience for debugging and for
// stable display of same-instant sends, NOT a correctness input anywhere in
// this package. The timestamps are the truth; see the package comment.
//
// Panics only on entropy-source failure or the ~infeasible case of more than
// 2^80 IDs inside one millisecond; both are programmer/environment failures,
// not runtime conditions worth an error path through every caller.
func NewID(at time.Time) string {
	idMu.Lock()
	defer idMu.Unlock()
	return ulid.MustNew(ulid.Timestamp(at), idEntropy).String()
}

// ValidateBody enforces the receiver-side body rule shared by every endpoint
// of req:text-messaging: at most [MaxBodyBytes] bytes of valid UTF-8.
//
// Exported because both directions need it — the coordinator rejects inbound
// violations with a structured ProtocolError naming the bound, and the client
// reuses the same check to refuse its own user's oversized draft before a
// round trip proves it undeliverable.
func ValidateBody(body string) error {
	if len(body) > MaxBodyBytes {
		return fmt.Errorf("body exceeds %d-byte bound (%d bytes)", MaxBodyBytes, len(body))
	}
	if !utf8.ValidString(body) {
		return fmt.Errorf("body is not valid UTF-8")
	}
	return nil
}
