// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: walkie/v1/control.proto

package walkiev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Envelope wraps every control-plane message.
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_id is a ULID generated by the sender. It makes redelivery
	// idempotent: the receiver discards a duplicate rather than the wire
	// preventing one. req:offline-delivery specifies at-least-once delivery with
	// receiver-side deduplication, so this field is load-bearing, not
	// diagnostic.
	MessageId string `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// sent_at is the sender's clock. Keep it even though it is untrustworthy:
	// clock skew across the fleet is expected, and req:text-messaging requires
	// retaining both this and the coordinator's receive time so the skew stays
	// legible to the user rather than being silently resolved.
	SentAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Hello
	//	*Envelope_HelloAck
	//	*Envelope_Heartbeat
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_walkie_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_walkie_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_walkie_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *Envelope) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *Envelope) GetHelloAck() *HelloAck {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_HelloAck); ok {
			return x.HelloAck
		}
	}
	return nil
}

func (x *Envelope) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Hello struct {
	Hello *Hello `protobuf:"bytes,10,opt,name=hello,proto3,oneof"`
}

type Envelope_HelloAck struct {
	HelloAck *HelloAck `protobuf:"bytes,11,opt,name=hello_ack,json=helloAck,proto3,oneof"`
}

type Envelope_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,12,opt,name=heartbeat,proto3,oneof"`
}

func (*Envelope_Hello) isEnvelope_Payload() {}

func (*Envelope_HelloAck) isEnvelope_Payload() {}

func (*Envelope_Heartbeat) isEnvelope_Payload() {}

// Hello opens a connection.
//
// It deliberately carries no credential of any kind. adr:004-security-model
// resolves the caller's identity from the tailnet with a WhoIs lookup on the
// connection's remote address, so there is no password, token or session
// identifier anywhere in this protocol. Adding one here would be a design
// regression, not a hardening step.
type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client_version is for diagnostics and compatibility reporting only. Never
	// branch protocol behaviour on it — that is what field-level compatibility
	// is for.
	ClientVersion string `protobuf:"bytes,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	// last_acked_position resumes the offline queue where this device left off,
	// instead of replaying everything. Zero means "I have nothing yet".
	// req:offline-delivery requires resumption by position.
	LastAckedPosition uint64 `protobuf:"varint,2,opt,name=last_acked_position,json=lastAckedPosition,proto3" json:"last_acked_position,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_walkie_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_walkie_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_walkie_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *Hello) GetLastAckedPosition() uint64 {
	if x != nil {
		return x.LastAckedPosition
	}
	return 0
}

// HelloAck completes the handshake.
type HelloAck struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device is the identity the coordinator resolved from the tailnet. The
	// client does not assert this; it learns it.
	Device string `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	// received_at is the coordinator's clock, the trustworthy half of the
	// timestamp pair.
	ReceivedAt *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=received_at,json=receivedAt,proto3" json:"received_at,omitempty"`
	// pending_count is how many queued messages are about to be delivered, so
	// the client can tell the user rather than appearing to hang.
	PendingCount  uint64 `protobuf:"varint,3,opt,name=pending_count,json=pendingCount,proto3" json:"pending_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloAck) Reset() {
	*x = HelloAck{}
	mi := &file_walkie_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloAck) ProtoMessage() {}

func (x *HelloAck) ProtoReflect() protoreflect.Message {
	mi := &file_walkie_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloAck.ProtoReflect.Descriptor instead.
func (*HelloAck) Descriptor() ([]byte, []int) {
	return file_walkie_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *HelloAck) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *HelloAck) GetReceivedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ReceivedAt
	}
	return nil
}

func (x *HelloAck) GetPendingCount() uint64 {
	if x != nil {
		return x.PendingCount
	}
	return 0
}

// Heartbeat keeps the connection observably alive.
//
// This is an application-level heartbeat and it is not redundant with TCP: a
// socket can stay open while the peer is gone. req:device-presence makes
// presence server-authoritative with a liveness TTL derived from these, which
// is why a client may not announce its own online state — a device that is
// killed cannot send a goodbye, and would otherwise appear online forever.
type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_walkie_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_walkie_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_walkie_v1_control_proto_rawDescGZIP(), []int{3}
}

var File_walkie_v1_control_proto protoreflect.FileDescriptor

const file_walkie_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x17walkie/v1/control.proto\x12\twalkie.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfd\x01\n" +
	"\bEnvelope\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x123\n" +
	"\asent_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12(\n" +
	"\x05hello\x18\n" +
	" \x01(\v2\x10.walkie.v1.HelloH\x00R\x05hello\x122\n" +
	"\thello_ack\x18\v \x01(\v2\x13.walkie.v1.HelloAckH\x00R\bhelloAck\x124\n" +
	"\theartbeat\x18\f \x01(\v2\x14.walkie.v1.HeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"^\n" +
	"\x05Hello\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\tR\rclientVersion\x12.\n" +
	"\x13last_acked_position\x18\x02 \x01(\x04R\x11lastAckedPosition\"\x84\x01\n" +
	"\bHelloAck\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12;\n" +
	"\vreceived_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"receivedAt\x12#\n" +
	"\rpending_count\x18\x03 \x01(\x04R\fpendingCount\"\v\n" +
	"\tHeartbeatBBZ@github.com/maleolabs/walkie/internal/genproto/walkie/v1;walkiev1b\x06proto3"

var (
	file_walkie_v1_control_proto_rawDescOnce sync.Once
	file_walkie_v1_control_proto_rawDescData []byte
)

func file_walkie_v1_control_proto_rawDescGZIP() []byte {
	file_walkie_v1_control_proto_rawDescOnce.Do(func() {
		file_walkie_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_walkie_v1_control_proto_rawDesc), len(file_walkie_v1_control_proto_rawDesc)))
	})
	return file_walkie_v1_control_proto_rawDescData
}

var file_walkie_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_walkie_v1_control_proto_goTypes = []any{
	(*Envelope)(nil),              // 0: walkie.v1.Envelope
	(*Hello)(nil),                 // 1: walkie.v1.Hello
	(*HelloAck)(nil),              // 2: walkie.v1.HelloAck
	(*Heartbeat)(nil),             // 3: walkie.v1.Heartbeat
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_walkie_v1_control_proto_depIdxs = []int32{
	4, // 0: walkie.v1.Envelope.sent_at:type_name -> google.protobuf.Timestamp
	1, // 1: walkie.v1.Envelope.hello:type_name -> walkie.v1.Hello
	2, // 2: walkie.v1.Envelope.hello_ack:type_name -> walkie.v1.HelloAck
	3, // 3: walkie.v1.Envelope.heartbeat:type_name -> walkie.v1.Heartbeat
	4, // 4: walkie.v1.HelloAck.received_at:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_walkie_v1_control_proto_init() }
func file_walkie_v1_control_proto_init() {
	if File_walkie_v1_control_proto != nil {
		return
	}
	file_walkie_v1_control_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Hello)(nil),
		(*Envelope_HelloAck)(nil),
		(*Envelope_Heartbeat)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_walkie_v1_control_proto_rawDesc), len(file_walkie_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_walkie_v1_control_proto_goTypes,
		DependencyIndexes: file_walkie_v1_control_proto_depIdxs,
		MessageInfos:      file_walkie_v1_control_proto_msgTypes,
	}.Build()
	File_walkie_v1_control_proto = out.File
	file_walkie_v1_control_proto_goTypes = nil
	file_walkie_v1_control_proto_depIdxs = nil
}
